const snackServings = 11;
const guests = 7;
console.log(snackServings + guests);
console.log(snackServings - guests);
console.log(guests - snackServings);

console.log(guests * snackServings);
console.log(snackServings / guests);
const drinks = 10;
const resultOne = (snackServings * guests) / drinks;
console.log(resultOne);
const monkeys = 15;
const bananas = 9;
console.log(monkeys / bananas);
const monkeyfights = 20;
const resultTwo = (monkeys + bananas) * monkeyfights;
console.log(resultTwo);
let monkeyBusiness = 90;
monkeyBusiness++;
let boredom = 13;
boredom--;
const happiness = monkeys - bananas;
console.log(happiness + monkeyfights);
console.log(resultOne / resultTwo);
